### ISSUE TITLE
作用

### ISSUE THREAD

**Issue by pqypqy** [zhaomenghuan/vue-html5plus#12]
您好，萌新问一下：官方plus可以直接用 为什么我们还需要安装你这个包呢 你这个包集成了啥 官方的api都能调用么 有啥区别没有

**Comment by NewsNIng** [comment]
@pqypqy 您好，此仓库原先是 Vue + HTMLPLUS5 的实例Demo程序，历史时间较长，更建议您直接阅读官方文档，此项目仓库可以做一些参考。
